<?php
declare(strict_types=1);
require_once __DIR__ . '/_admin_auth.php';
require_once __DIR__ . '/../../includes/work_tracker.php';
require_once __DIR__ . '/../../includes/work_social_video.php';
header('Content-Type: application/json; charset=utf-8');
function sv_fail(string $m,int $s=400): never {http_response_code($s);echo json_encode(['ok'=>false,'error'=>$m]);exit;}
function sv_visual_data_url(string $path,string $mime):?string{
    if(!extension_loaded('gd'))return null;$source=wt_load_gd_image($path,$mime);if(!$source)return null;
    $source=wt_apply_jpeg_orientation($source,$path,$mime);$w=imagesx($source);$h=imagesy($source);if($w<1||$h<1)return null;
    $scale=min(1,512/max($w,$h));$outW=max(1,(int)round($w*$scale));$outH=max(1,(int)round($h*$scale));
    $canvas=imagecreatetruecolor($outW,$outH);$white=imagecolorallocate($canvas,255,255,255);imagefilledrectangle($canvas,0,0,$outW,$outH,$white);imagecopyresampled($canvas,$source,0,0,0,0,$outW,$outH,$w,$h);
    ob_start();imagejpeg($canvas,null,68);$bytes=ob_get_clean();imagedestroy($canvas);if(is_resource($source)||is_object($source))@imagedestroy($source);
    return is_string($bytes)&&$bytes!==''?'data:image/jpeg;base64,'.base64_encode($bytes):null;
}
function sv_public_area(array $job):string{
    $site=trim((string)($job['site_name']??''));if($site!=='')return mb_substr($site,0,80);
    $address=trim((string)($job['job_address']??''));
    if(preg_match("/\\b(?:Street|St|Road|Rd|Avenue|Ave|Boulevard|Blvd|Drive|Dr|Court|Ct|Crescent|Cres|Lane|Ln|Place|Pl|Way|Highway|Hwy)\\s+([A-Za-z][A-Za-z\\s'-]{2,})\\s+\\d{4}\\b/i",$address,$m))return trim($m[1]);
    if(preg_match("/\\b([A-Za-z][A-Za-z'-]*(?:\\s+[A-Za-z][A-Za-z'-]*)?)\\s+\\d{4}\\b/",$address,$m))return trim($m[1]);
    return '';
}
if($_SERVER['REQUEST_METHOD']!=='POST')sv_fail('POST required.',405);
$jobId=(int)($_POST['job_id']??0);$platform=(string)($_POST['platform']??'');$voice=(string)($_POST['voiceover_enabled']??'0')==='1';$baseSeconds=max(1.0,min(3.0,(float)($_POST['image_seconds']??1.8)));
if($jobId<=0||!isset(wt_social_video_platforms()[$platform]))sv_fail('Invalid job or platform.');
preg_match_all('/\d+/',(string)($_POST['photo_ids']??''),$m);$ids=array_values(array_unique(array_map('intval',$m[0]??[])));if(count($ids)<2||count($ids)>50)sv_fail('Choose between 2 and 50 photos.');
$job=wt_job($pdo,$jobId);$marks=implode(',',array_fill(0,count($ids),'?'));$q=$pdo->prepare("SELECT p.id,p.photo_type,p.note,p.created_at,p.relative_path,p.mime_type,p.file_deleted_at,t.title task_title,t.description task_description FROM work_task_photos p LEFT JOIN work_tasks t ON t.id=p.task_id WHERE p.job_id=? AND p.id IN ($marks)");$q->execute(array_merge([$jobId],$ids));$found=[];foreach($q->fetchAll(PDO::FETCH_ASSOC) as $p){if(empty($p['file_deleted_at'])&&is_file(wt_task_photo_path((string)$p['relative_path'])))$found[(int)$p['id']]=$p;}foreach($ids as $pid)if(!isset($found[$pid]))sv_fail('Photo #'.$pid.' has no usable source file.');
$selectedPosition=array_flip($ids);$stageRank=['before'=>0,'progress'=>1,'after'=>2];usort($ids,static function(int $a,int $b)use($found,$selectedPosition,$stageRank):int{$aStage=(string)($found[$a]['photo_type']??'progress');$bStage=(string)($found[$b]['photo_type']??'progress');$rankComparison=($stageRank[$aStage]??1)<=>($stageRank[$bStage]??1);return $rankComparison!==0?$rankComparison:(($selectedPosition[$a]??0)<=>($selectedPosition[$b]??0));});
$photos=[];foreach($ids as $pid){$p=$found[$pid];$photos[]=['id'=>$pid,'stage'=>wt_photo_stage_label((string)$p['photo_type']),'task'=>(string)($p['task_title']??''),'task_description'=>(string)($p['task_description']??''),'photo_note'=>(string)($p['note']??''),'created_at'=>(string)$p['created_at']];}
$key=trim((string)wt_env('OPENAI_API_KEY',''));if($key==='')sv_fail('OPENAI_API_KEY is not configured.',500);
$context=['business'=>'Mike Of All Trades, handyman/property maintenance in Victoria, Australia','platform'=>$platform,'voiceover'=>$voice,'public_location_area'=>sv_public_area($job),'customer_request'=>(string)($job['customer_request_text']??$job['original_scope']??''),'current_scope'=>(string)($job['current_scope']??''),'selected_photos_in_required_order'=>$photos];
$largeSelection=count($ids)>25;
$voiceTimingRule=$largeSelection
    ? 'This is a large selection. Use 1.2 to 2.0 seconds per photo. Organise consecutive photos within each stage into visual scenes of roughly 2 to 5 images. Put narration_text on the first image of a scene and use an empty string on the remaining images. Repeat that exact narration_text as screen_caption across every image in its scene. Each narrated scene should normally be 5 to 12 words.'
    : 'Use roughly 1.5 to 2.5 seconds per photo. Group related consecutive images within each stage into scenes. Put narration_text on the first image of a scene, use an empty string on the remaining images, and repeat that exact narration_text as screen_caption across the scene.';
$prompt='Create a high-energy vertical social slideshow plan from these real job records AND the attached images. Return JSON only: {"title":"","post_caption":"","hashtags":["#tag"],"items":[{"photo_id":1,"screen_caption":"","narration_text":"","duration_seconds":1.8}]}. Visually inspect every attached photo and combine that evidence with the written task information. The supplied order is mandatory and has already been grouped as all BEFORE photos, then all IN PROGRESS photos, then all AFTER photos. Preserve that order and include every selected photo exactly once. Build one chronological story across the stages that are actually present. At the first BEFORE scene, explain conversationally that this is what Mike encountered or what the client asked him to address, grounded in the records and visible evidence. At the first IN PROGRESS scene, explain that Mike is working through the relevant repairs, maintenance, preparation, enhancements or improvements, using only details supported by the records and images. At the first AFTER scene, explain that Mike has finished the supported work and describe the visible finished result. End the final scene with a concise invitation to contact Mike of All Trades through his website or mobile phone for help at the viewer\'s property. Do not claim a stage exists when no selected photo has that stage. You may describe clearly visible, non-sensitive context such as interior or exterior, room/area type, colours, materials or surfaces, cosmetic condition, preparation, progression and visible transformation. Use the public_location_area naturally when useful, but never reveal or infer a street address. Treat structural, safety, moisture, electrical, plumbing and causation claims as unknown unless explicitly supported by the written record; say appears, looks or visible when interpretation is uncertain. Use only supplied photo IDs; never invent unseen defects, methods, danger, savings, customer reactions or results; never expose customer name, exact address or private details; do not imply Mike performed licensed work. Write a powerful truthful curiosity-gap title and a vivid, persuasive story-driven post caption. For voice-over reels, visible captions must match the spoken words: whenever narration_text is non-empty, screen_caption must contain exactly the same text. On following photos in that scene, repeat the same screen_caption and leave narration_text empty so the words are spoken once. Narration should be warm, confident and conversational. If voiceover is false set every duration_seconds to '.number_format($baseSeconds,1,'.','').' and use concise screen captions; if voiceover is true: '.$voiceTimingRule.' Keep estimated total under 90 seconds. Context: '.json_encode($context,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
$content=[['type'=>'input_text','text'=>$prompt]];foreach($ids as $pid){$p=$found[$pid];$content[]=['type'=>'input_text','text'=>'The next image is photo_id '.$pid.'; recorded stage '.wt_photo_stage_label((string)$p['photo_type']).'; task '.trim((string)($p['task_title']??'')).'; note '.trim((string)($p['note']??'')).'.'];$dataUrl=sv_visual_data_url(wt_task_photo_path((string)$p['relative_path']),(string)$p['mime_type']);if($dataUrl!==null)$content[]=['type'=>'input_image','image_url'=>$dataUrl,'detail'=>'low'];}
$model=wt_env('WORKTRACKER_SOCIAL_VIDEO_AI_MODEL',wt_env('WORKTRACKER_SOCIAL_AI_MODEL',wt_env('WORKTRACKER_AI_MODEL','gpt-5.6-luna')));$payload=json_encode(['model'=>$model,'input'=>[['role'=>'user','content'=>$content]],'max_output_tokens'=>5000],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
$ch=curl_init('https://api.openai.com/v1/responses');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$payload,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>120,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$key,'Content-Type: application/json']]);$raw=curl_exec($ch);$err=curl_error($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($raw===false||$status<200||$status>=300)sv_fail($err?:'OpenAI request failed with HTTP '.$status,502);
$data=json_decode((string)$raw,true);$text='';foreach(($data['output']??[]) as $out)foreach(($out['content']??[]) as $c)if(isset($c['text']))$text.=$c['text'];$text=trim((string)preg_replace('/^```(?:json)?\s*|\s*```$/i','',trim($text)));$plan=json_decode($text,true);if(!is_array($plan)||empty($plan['items']))sv_fail('AI returned an invalid slideshow plan.',502);
$byId=[];foreach($plan['items'] as $item)$byId[(int)($item['photo_id']??0)]=$item;$items=[];$total=0.0;$previousScreen='';$previousStage='';foreach($ids as $pid){if(!isset($byId[$pid]))sv_fail('AI omitted a selected photo. Please generate again.',502);$it=$byId[$pid];$stage=(string)($found[$pid]['photo_type']??'progress');$screen=mb_substr(trim((string)($it['screen_caption']??'')),0,220);$narr=mb_substr(trim((string)($it['narration_text']??'')),0,220);if($voice){if($stage!==$previousStage&&$narr==='')$narr=$screen;if($narr!=='')$screen=$narr;elseif($previousScreen!=='')$screen=$previousScreen;}if($screen==='')$screen=$previousScreen?:wt_photo_stage_label($stage);$previousScreen=$screen;$previousStage=$stage;$suggested=(float)($it['duration_seconds']??1.8);$duration=$voice?($largeSelection?max(1.2,min(2.0,$suggested)):max(1.5,min(3.5,$suggested))):$baseSeconds;$total+=$duration;$items[]=['photo_id'=>$pid,'screen_caption'=>$screen,'narration_text'=>$narr,'duration_seconds'=>round($duration,1)];}if($voice&&$items){$last=count($items)-1;$lastNarr=trim((string)$items[$last]['narration_text']);$cta='Need help at your property? Contact Mike of All Trades through his website or mobile phone.';$hasMikeCta=stripos($lastNarr,'Mike of All Trades')!==false&&preg_match('/\b(?:contact|website|mobile|phone)\b/i',$lastNarr);if(!$hasMikeCta)$lastNarr=trim(mb_substr($lastNarr,0,max(0,219-mb_strlen($cta))).' '.$cta);$lastNarr=mb_substr($lastNarr,0,220);$items[$last]['narration_text']=$lastNarr;$items[$last]['screen_caption']=$lastNarr;}if($total>95)sv_fail('This selection would exceed about 90 seconds. Choose fewer photos or shorten narration.',400);
$plan=['title'=>mb_substr(trim((string)($plan['title']??'Real job progress')),0,255),'post_caption'=>trim((string)($plan['post_caption']??'')),'hashtags'=>array_values(array_filter(array_map('strval',(array)($plan['hashtags']??[])))),'items'=>$items,'ai_model'=>$model,'raw_ai'=>$text];echo json_encode(['ok'=>true,'plan'=>$plan],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
