<?php
declare(strict_types=1);
require_once __DIR__.'/_admin_auth.php';require_once __DIR__.'/../../includes/work_tracker.php';require_once __DIR__.'/../../includes/work_invoice.php';require_once __DIR__.'/../../includes/zoho_functions.php';
if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);exit('POST required.');}$jobIds=array_values(array_filter(array_map('intval',explode(',',(string)($_POST['job_ids']??($_POST['job_id']??'')))),fn($id)=>$id>0));$jobId=$jobIds[0]??0;$snapshotId=(int)($_POST['snapshot_id']??0);$returnUrl=count($jobIds)>1?'../../admin/work/combined_invoice_preparation.php?customer_id='.(int)($_POST['customer_id']??0).'&'.http_build_query(['job_ids'=>$jobIds]):'../../admin/work/invoice_preparation.php?id='.$jobId;if($jobId<=0||$snapshotId<=0){http_response_code(400);exit('Invalid request.');}
$lockName='work_zoho_invoice_'.$jobId;$lock=$pdo->prepare('SELECT GET_LOCK(?,10)');$lock->execute([$lockName]);if((int)$lock->fetchColumn()!==1){http_response_code(409);exit('Another invoice request is running.');}
try{$q=$pdo->prepare('SELECT * FROM work_closeout_snapshots WHERE id=? AND job_id=?');$q->execute([$snapshotId,$jobId]);$snapshot=$q->fetch(PDO::FETCH_ASSOC);if(!$snapshot||empty($snapshot['zoho_invoice_id']))throw new RuntimeException('Zoho draft not found.');if(!empty($snapshot['sent_to_zoho_at']))throw new RuntimeException('This invoice was already emailed and cannot be silently changed.');
$package=wt_invoice_package_for_jobs($pdo,$jobIds);$job=$package['job'];$contactId=wt_invoice_zoho_contact_id($package);$response=updateZohoInvoice((string)$snapshot['zoho_invoice_id'],wt_invoice_zoho_payload($package,(string)$contactId,getZohoZeroTaxId()));$invoice=$response['json']['invoice']??null;if(!is_array($invoice))throw new RuntimeException('Zoho draft update failed: '.mb_substr((string)($response['raw']??'Unknown response'),0,1000));wt_assert_zoho_invoice_matches($invoice,$package);
$saved=json_encode(['schema_version'=>3,'captured_at'=>date('c'),'invoice_package'=>$package],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$meta=json_decode((string)($snapshot['zoho_response_json']??''),true);if(!is_array($meta))$meta=[];$meta['update_response']=$response['json'];$meta['invoice_number']=$invoice['invoice_number']??($meta['invoice_number']??null);$meta['updated_at']=date('c');$q=$pdo->prepare('UPDATE work_closeout_snapshots SET labour_amount=?,materials_amount=?,gross_job_amount=?,payments_amount=?,outstanding_amount=?,snapshot_json=?,zoho_response_json=? WHERE id=? AND job_id=?');$q->execute([$package['totals']['labour'],$package['totals']['reimbursements'],$package['totals']['invoice_total'],$package['totals']['payments'],$package['totals']['balance_due'],$saved,json_encode($meta,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$snapshotId,$jobId]);header('Location: '.$returnUrl.'&zoho_synced=1#zoho-invoice');}
catch(Throwable $e){error_log('Zoho invoice sync failed: '.$e->getMessage());header('Location: '.$returnUrl.'&zoho_error='.urlencode($e->getMessage()).'#zoho-invoice');}
finally{$q=$pdo->prepare('SELECT RELEASE_LOCK(?)');$q->execute([$lockName]);}
