<?php
declare(strict_types=1);
require_once __DIR__.'/_auth.php';require_once __DIR__.'/../../includes/work_tracker.php';require_once __DIR__.'/../../includes/work_invoice.php';
$customerId=(int)($_GET['customer_id']??0);$customer=wt_customer($pdo,$customerId);$jobIds=array_values(array_filter(array_map('intval',(array)($_GET['job_ids']??[])),fn($id)=>$id>0));if(!$jobIds)throw new RuntimeException('Select at least one job.');
$package=wt_invoice_package_for_jobs($pdo,$jobIds);if((int)$package['customer']['id']!==$customerId)throw new RuntimeException('Selected jobs do not belong to this customer.');$primary=$jobIds[0];$jobIdsCsv=implode(',',$jobIds);
$q=$pdo->prepare('SELECT * FROM work_closeout_snapshots WHERE job_id=? AND zoho_invoice_id IS NOT NULL ORDER BY id DESC LIMIT 20');$q->execute([$primary]);$latest=null;foreach($q->fetchAll(PDO::FETCH_ASSOC) as $s){$saved=json_decode((string)$s['snapshot_json'],true);if(($saved['invoice_package']['fingerprint']??'')===$package['fingerprint']){$latest=$s;break;}}
$days=(int)$package['customer']['payment_terms_days'];$invoiceDate=date('Y-m-d');$dueDate=date('Y-m-d',strtotime($invoiceDate.' +'.$days.' days'));
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Combined invoice — <?=wt_html($customer['display_name'])?></title><style>
body{font-family:system-ui;background:#eef2f4;color:#17202a;margin:0}.wrap{max-width:1150px;margin:auto;padding:18px}.card{background:#fff;border-radius:14px;padding:18px;margin:13px 0;box-shadow:0 2px 10px #0001}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:9px}.metric{background:#f7f9fa;border:1px solid #dfe6ea;border-radius:10px;padding:12px}.metric b{display:block;font-size:21px}.btn{display:inline-block;background:#17202a;color:#fff;border:0;border-radius:9px;padding:10px 13px;font-weight:800;text-decoration:none;cursor:pointer}.secondary{background:#fff;color:#17202a;border:1px solid #cbd5dc}.notice{padding:12px;border-radius:9px;background:#fff4d6;border:1px solid #efc451}.good{background:#edf8f0;border-color:#96d0a4}.danger{background:#ffeded;border-color:#e69b9b}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #e2e8ed;text-align:left}.money{text-align:right;white-space:nowrap}.muted{color:#667681;font-size:13px}@media(max-width:700px){.metrics{grid-template-columns:1fr 1fr}.wrap{padding:10px}}
</style></head><body><?php $adminPageTitle='Combined invoice preparation';$adminBreadcrumbs=['Work Tracker'=>'index.php','Customer'=>'customer.php?id='.$customerId,'Combined invoice'=>''];$adminJob=wt_job($pdo,$primary);require __DIR__.'/../../includes/admin_nav.php';?><main class="wrap">
<p><a class="btn secondary" href="customer.php?id=<?=$customerId?>">← CUSTOMER &amp; JOBS</a></p><div class="card"><h1>Combined invoice — <?=wt_html($customer['display_name'])?></h1><p class="muted">Each job and property remains separate. Only this invoice combines the selected charges.</p><table><thead><tr><th>Job</th><th>Property/site</th></tr></thead><tbody><?php foreach($package['jobs'] as $j):?><tr><td>#<?=(int)$j['id']?> — <?=wt_html($j['alias'])?></td><td><?=wt_html($j['address'])?></td></tr><?php endforeach;?></tbody></table></div>
<div class="card"><h2>Invoice settings and safety check</h2><div class="metrics"><div class="metric">Terms<b><?=wt_html(wt_payment_terms_label($days))?></b></div><div class="metric">Invoice date<b><?=wt_html(date('d/m/Y',strtotime($invoiceDate)))?></b></div><div class="metric">Due date<b><?=wt_html(date('d/m/Y',strtotime($dueDate)))?></b></div><div class="metric">Total — no GST<b><?=wt_money((float)$package['totals']['invoice_total'])?></b></div></div><?php if(empty($package['customer']['zoho_contact_id'])):?><p class="notice danger">Link this customer to the correct existing Zoho customer before creating a draft. <a href="customer.php?id=<?=$customerId?>">Open customer record</a>.</p><?php else:?><p class="notice good">Zoho customer linked: <?=wt_html((string)$customer['zoho_contact_name'])?>. This exact contact will be reused.</p><?php endif;?></div>
<div class="card"><h2>Charges by job/property</h2><table><thead><tr><th>Item</th><th>Description</th><th class="money">Amount</th></tr></thead><tbody><?php foreach($package['labour_days'] as $d):?><tr><td>Labour — <?=wt_html(date('j M Y',strtotime($d['date'])))?></td><td><?=wt_html($d['description'])?></td><td class="money"><?=wt_money((float)$d['amount'])?></td></tr><?php endforeach;?><?php foreach($package['reimbursements'] as $g):?><tr><td>Reimbursement — <?=wt_html($g['supplier'])?></td><td><?=wt_html(implode('; ',$g['items']))?></td><td class="money"><?=wt_money((float)$g['amount'])?></td></tr><?php endforeach;?></tbody><tfoot><tr><th colspan="2">Total — no GST</th><th class="money"><?=wt_money((float)$package['totals']['invoice_total'])?></th></tr></tfoot></table></div>
<div class="card" id="zoho-invoice"><h2>Zoho invoice</h2><?php if(isset($_GET['zoho_created'])):?><p class="notice good">Zoho draft created. Nothing has been emailed.</p><?php endif;?><?php if(isset($_GET['zoho_synced'])):?><p class="notice good">Zoho draft synchronised. Nothing has been emailed.</p><?php endif;?><?php if(isset($_GET['zoho_sent'])):?><p class="notice good">Zoho invoice emailed successfully.</p><?php endif;?><?php if(isset($_GET['zoho_existing'])):?><p class="notice">An identical draft already exists; no duplicate was created.</p><?php endif;?><?php if(isset($_GET['zoho_error'])):?><p class="notice danger"><b>Zoho action stopped:</b> <?=wt_html((string)$_GET['zoho_error'])?></p><?php endif;?>
<?php if($latest):$meta=json_decode((string)($latest['zoho_response_json']??''),true)?:[];?><p><b>Invoice:</b> <?=wt_html((string)($meta['invoice_number']??$latest['zoho_invoice_id']))?><br><b>Status:</b> <?=empty($latest['sent_to_zoho_at'])?'DRAFT — NOT EMAILED':'EMAILED '.wt_html((string)$latest['sent_to_zoho_at'])?></p><?php if(empty($latest['sent_to_zoho_at'])):?><form style="display:inline" method="post" action="../../api/work/sync_zoho_invoice.php"><input type="hidden" name="job_ids" value="<?=wt_html($jobIdsCsv)?>"><input type="hidden" name="customer_id" value="<?=$customerId?>"><input type="hidden" name="snapshot_id" value="<?=(int)$latest['id']?>"><button class="btn secondary">SYNC CURRENT ZOHO DRAFT</button></form> <form style="display:inline" method="post" action="../../api/work/send_zoho_invoice.php" onsubmit="return confirm('Email this combined invoice to <?=wt_html($package['customer']['email'])?> now?');"><input type="hidden" name="job_ids" value="<?=wt_html($jobIdsCsv)?>"><input type="hidden" name="customer_id" value="<?=$customerId?>"><input type="hidden" name="snapshot_id" value="<?=(int)$latest['id']?>"><button class="btn">SEND ZOHO INVOICE TO CUSTOMER</button></form><?php endif;?><?php else:?><form method="post" action="../../api/work/create_zoho_invoice.php" onsubmit="return confirm('Create one Zoho draft for these selected jobs? Nothing will be emailed.');"><input type="hidden" name="job_ids" value="<?=wt_html($jobIdsCsv)?>"><input type="hidden" name="customer_id" value="<?=$customerId?>"><button class="btn" <?=empty($package['customer']['zoho_contact_id'])||$package['warnings']['unfinished_sessions']>0?'disabled':''?>>CREATE COMBINED ZOHO DRAFT — DO NOT EMAIL</button></form><?php endif;?></div>
</main></body></html>
