<?php
declare(strict_types=1);
require_once __DIR__.'/_auth.php';require_once __DIR__.'/../../includes/work_tracker.php';
$id=(int)($_GET['id']??0);$customer=wt_customer($pdo,$id);
$q=$pdo->prepare('SELECT * FROM work_properties WHERE customer_id=? ORDER BY id');$q->execute([$id]);$properties=$q->fetchAll(PDO::FETCH_ASSOC);
$q=$pdo->prepare("SELECT j.*,(SELECT COUNT(*) FROM work_invoice_jobs ij JOIN work_invoice_ledger i ON i.id=ij.invoice_id WHERE ij.job_id=j.id) invoice_count FROM work_jobs j WHERE j.customer_id=? ORDER BY COALESCE(j.last_opened_at,j.updated_at) DESC,j.id DESC");$q->execute([$id]);$jobs=$q->fetchAll(PDO::FETCH_ASSOC);
$q=$pdo->prepare("SELECT i.*,GROUP_CONCAT(CONCAT('#',j.id,' ',j.job_address) ORDER BY j.id SEPARATOR ' | ') jobs FROM work_invoice_ledger i LEFT JOIN work_invoice_jobs ij ON ij.invoice_id=i.id LEFT JOIN work_jobs j ON j.id=ij.job_id WHERE i.customer_id=? GROUP BY i.id ORDER BY i.invoice_date DESC,i.id DESC");$q->execute([$id]);$invoices=$q->fetchAll(PDO::FETCH_ASSOC);
$otherJobs=$pdo->prepare('SELECT id,customer_name,job_address FROM work_jobs WHERE customer_id<>? OR customer_id IS NULL ORDER BY id DESC LIMIT 200');$otherJobs->execute([$id]);$otherJobs=$otherJobs->fetchAll(PDO::FETCH_ASSOC);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Customer — <?=wt_html($customer['display_name'])?></title><style>
body{font-family:system-ui;background:#eef2f4;color:#17202a;margin:0}.wrap{max-width:1100px;margin:auto;padding:18px}.card{background:#fff;border-radius:14px;padding:18px;margin:13px 0;box-shadow:0 2px 10px #0001}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:11px}.wide{grid-column:1/-1}label{display:block;font-size:12px;font-weight:800;margin-bottom:4px}input,select,textarea{width:100%;box-sizing:border-box;padding:10px;border:1px solid #cbd5dc;border-radius:8px;font:inherit}.btn{display:inline-block;background:#17202a;color:#fff;border:0;border-radius:9px;padding:10px 13px;font-weight:800;text-decoration:none;cursor:pointer}.secondary{background:#fff;color:#17202a;border:1px solid #cbd5dc}.notice{padding:11px;border-radius:9px;background:#edf8f0;border:1px solid #96d0a4}.job{display:flex;justify-content:space-between;gap:10px;align-items:center;border-top:1px solid #e2e8ed;padding:11px 0}.muted{color:#667681;font-size:13px}.zoho-result{border:1px solid #d5dde3;border-radius:9px;padding:10px;margin:8px 0}@media(max-width:700px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.job{display:block}}
</style></head><body><?php $adminPageTitle='Customer: '.$customer['display_name'];$adminBreadcrumbs=['Work Tracker'=>'index.php','Customer'=>''];require __DIR__.'/../../includes/admin_nav.php';?><main class="wrap">
<?php if(isset($_GET['saved'])):?><p class="notice">Customer and property details saved.</p><?php endif;?><?php if(isset($_GET['zoho_linked'])):?><p class="notice">Existing Zoho customer linked. Future invoices will reuse that exact Zoho contact.</p><?php endif;?><?php if(isset($_GET['job_linked'])):?><p class="notice">Job and its property linked to this customer.</p><?php endif;?>
<div class="card"><h1><?=wt_html($customer['display_name'])?></h1><p class="muted">One customer can have multiple properties and jobs. Job source names remain visible for history.</p><form method="post" action="../../api/work/update_customer.php"><input type="hidden" name="customer_id" value="<?=$id?>"><input type="hidden" name="action" value="save"><div class="grid">
<div><label>Full billing name</label><input name="display_name" required value="<?=wt_html($customer['display_name'])?>"></div><div><label>Original/source alias</label><input name="source_alias" value="<?=wt_html((string)$customer['source_alias'])?>" placeholder="e.g. Kuma D. from Airtasker"></div>
<div><label>Organisation</label><input name="organisation" value="<?=wt_html((string)$customer['organisation'])?>"></div><div><label>Email</label><input type="email" name="email" value="<?=wt_html((string)$customer['email'])?>"></div>
<div><label>Phone</label><input name="phone" value="<?=wt_html((string)$customer['phone'])?>"></div><div><label>Payment terms</label><select id="termsPreset"><option value="0">Due on Receipt</option><option value="7">Net 7</option><option value="14">Net 14</option><option value="15">Net 15</option><option value="30">Net 30</option><option value="custom">Custom</option></select><input id="termsDays" type="number" min="0" max="365" name="payment_terms_days" value="<?=(int)$customer['payment_terms_days']?>" aria-label="Payment terms in days"></div>
<div class="wide"><label>Billing address</label><textarea name="billing_address" rows="2"><?=wt_html((string)$customer['billing_address'])?></textarea></div></div>
<h2>Properties</h2><?php foreach($properties as $p):?><div class="grid"><div><label>Property label</label><input name="property_label[<?=(int)$p['id']?>]" value="<?=wt_html((string)$p['label'])?>" placeholder="Home, rental, office…"></div><div><label>Property address</label><input name="property_address[<?=(int)$p['id']?>]" value="<?=wt_html($p['address'])?>"></div></div><?php endforeach;?><p><button class="btn">SAVE CUSTOMER &amp; PROPERTIES</button></p></form></div>
<div class="card"><h2>Zoho customer connection</h2><?php if(!empty($customer['zoho_contact_id'])):?><p class="notice"><b>Linked:</b> <?=wt_html((string)$customer['zoho_contact_name'])?> · Zoho ID <?=wt_html((string)$customer['zoho_contact_id'])?></p><?php else:?><p class="muted">Search and deliberately select an existing Zoho customer. Nothing is merged or created automatically.</p><div class="grid"><div><label>Search Zoho by name, email or phone</label><input id="zohoSearch" value="<?=wt_html($customer['display_name'])?>"></div><div style="align-self:end"><button class="btn secondary" type="button" id="zohoSearchButton">SEARCH ZOHO</button></div></div><div id="zohoResults"></div><?php endif;?></div>
<div class="card"><h2>Jobs and next invoice</h2><p class="muted">Jobs remain available for progress invoicing. Labour and materials already reconciled to an invoice are automatically excluded.</p><form method="get" action="combined_invoice_preparation.php"><input type="hidden" name="customer_id" value="<?=$id?>"><?php foreach($jobs as $j):?><div class="job"><label><input style="width:auto" type="checkbox" name="job_ids[]" value="<?=(int)$j['id']?>"> <b>Job #<?=(int)$j['id']?> — <?=wt_html($j['customer_name'])?></b><br><span class="muted"><?=wt_html($j['job_address'])?> · <?=wt_html($j['status'])?><?=(int)$j['invoice_count']>0?' · '.(int)$j['invoice_count'].' linked invoice(s)':''?></span></label><a class="btn secondary" href="manage_job.php?id=<?=(int)$j['id']?>">OPEN JOB</a></div><?php endforeach;?><?php if($jobs):?><p><button class="btn">PREPARE ONE COMBINED INVOICE FOR SELECTED JOBS</button></p><?php endif;?></form></div>
<div class="card"><h2>Invoice history</h2><?php foreach($invoices as $invoice):?><div class="job"><div><b><?=wt_html($invoice['invoice_number'])?></b> · <?=wt_html(strtoupper($invoice['status']))?> · <?=wt_money((float)$invoice['total_amount'])?><br><span class="muted"><?=wt_html((string)$invoice['jobs'])?><?=empty($invoice['reconciled_at'])?' · NEEDS RECONCILIATION':' · RECONCILED'?></span></div><a class="btn secondary" href="invoice_reconciliation.php?id=<?=(int)$invoice['id']?>"><?=empty($invoice['reconciled_at'])?'RECONCILE':'REVIEW'?></a></div><?php endforeach;?><?php if(!$invoices):?><p class="muted">No invoices are linked to this customer yet.</p><?php endif;?></div>
<div class="card"><h2>Link an existing Zoho invoice</h2><p class="muted">Use this for a progress invoice that was created before ezTradie invoice tracking. It imports the invoice header first, then asks you to select the exact labour and materials it covered.</p><?php if(empty($customer['zoho_contact_id'])):?><p>Link the Zoho customer above first.</p><?php else:?><form method="post" action="../../api/work/import_zoho_invoice.php" onsubmit="return confirm('Import this existing Zoho invoice? It will not alter or resend the invoice.');"><input type="hidden" name="customer_id" value="<?=$id?>"><label>Zoho invoice number</label><input name="invoice_number" required placeholder="INV-000185"><p><b>Related jobs</b></p><?php foreach($jobs as $j):?><label><input style="width:auto" type="checkbox" name="job_ids[]" value="<?=(int)$j['id']?>"> Job #<?=(int)$j['id']?> — <?=wt_html($j['job_address'])?></label><?php endforeach;?><p><button class="btn">IMPORT AND RECONCILE INVOICE</button></p></form><?php endif;?></div>
<div class="card"><h2>Link another existing job</h2><p class="muted">Use this for another property or job belonging to the same person. The job, photos and records stay separate.</p><form method="post" action="../../api/work/update_customer.php" onsubmit="return confirm('Link this job and its property to <?=wt_html($customer['display_name'])?>?');"><input type="hidden" name="customer_id" value="<?=$id?>"><input type="hidden" name="action" value="link_job"><select name="job_id" required><option value="">Choose a job…</option><?php foreach($otherJobs as $j):?><option value="<?=(int)$j['id']?>">Job #<?=(int)$j['id']?> — <?=wt_html($j['customer_name'].' — '.$j['job_address'])?></option><?php endforeach;?></select><p><button class="btn">LINK JOB TO THIS CUSTOMER</button></p></form></div>
</main><script>
const days=document.getElementById('termsDays'),preset=document.getElementById('termsPreset');if(['0','7','14','15','30'].includes(days.value))preset.value=days.value;else preset.value='custom';preset.addEventListener('change',()=>{if(preset.value!=='custom')days.value=preset.value;});
const searchButton=document.getElementById('zohoSearchButton');if(searchButton)searchButton.addEventListener('click',async()=>{const box=document.getElementById('zohoResults');box.textContent='Searching…';try{const r=await fetch('../../api/work/search_zoho_customers.php?q='+encodeURIComponent(document.getElementById('zohoSearch').value),{credentials:'same-origin'});const data=await r.json();if(!data.ok)throw new Error(data.error||'Search failed');box.innerHTML='';if(!data.contacts.length){box.textContent='No matching Zoho customers found.';return;}data.contacts.forEach(c=>{const form=document.createElement('form');form.method='post';form.action='../../api/work/update_customer.php';form.className='zoho-result';form.innerHTML='<input type="hidden" name="customer_id" value="<?=$id?>"><input type="hidden" name="action" value="link_zoho"><input type="hidden" name="zoho_contact_id" value="'+c.contact_id+'"><b></b><div class="muted"></div><button class="btn" type="submit">LINK THIS ZOHO CUSTOMER</button>';form.querySelector('b').textContent=c.name;form.querySelector('.muted').textContent=[c.email,c.phone,'Zoho ID '+c.contact_id].filter(Boolean).join(' · ');form.onsubmit=()=>confirm('Link this exact Zoho customer? Future invoices will use it and no duplicate will be created.');box.appendChild(form);});}catch(e){box.textContent=e.message;}});
</script></body></html>
