<?php
declare(strict_types=1);require_once __DIR__.'/_auth.php';require_once __DIR__.'/../../includes/work_tracker.php';
$id=(int)($_GET['id']??0);$q=$pdo->prepare('SELECT i.*,c.display_name FROM work_invoice_ledger i JOIN work_customers c ON c.id=i.customer_id WHERE i.id=?');$q->execute([$id]);$invoice=$q->fetch(PDO::FETCH_ASSOC);if(!$invoice){http_response_code(404);exit('Invoice not found.');}
$q=$pdo->prepare('SELECT j.id,j.job_address,j.customer_name FROM work_invoice_jobs ij JOIN work_jobs j ON j.id=ij.job_id WHERE ij.invoice_id=? ORDER BY j.id');$q->execute([$id]);$jobs=$q->fetchAll(PDO::FETCH_ASSOC);$jobIds=array_map('intval',array_column($jobs,'id'));$marks=implode(',',array_fill(0,count($jobIds),'?'));
$q=$pdo->prepare("SELECT s.id,s.job_id,s.started_at,s.ended_at,s.notes,t.title,COALESCE(w.hourly_rate,j.agreed_hourly_rate,0) rate,CASE WHEN s.ended_at IS NULL THEN 0 WHEN s.session_source='retrospective' AND s.retrospective_hours IS NOT NULL THEN s.retrospective_hours ELSE GREATEST(0,TIMESTAMPDIFF(SECOND,s.started_at,s.ended_at)-COALESCE((SELECT SUM(TIMESTAMPDIFF(SECOND,b.started_at,COALESCE(b.ended_at,s.ended_at))) FROM work_session_breaks b WHERE b.session_id=s.id),0))/3600 END hours,EXISTS(SELECT 1 FROM work_invoice_sessions x WHERE x.invoice_id=? AND x.session_id=s.id) selected FROM work_sessions s JOIN work_jobs j ON j.id=s.job_id LEFT JOIN work_tasks t ON t.id=s.task_id LEFT JOIN work_workers w ON w.id=s.worker_id WHERE s.job_id IN ($marks) AND s.ended_at IS NOT NULL AND s.billable=1 AND NOT EXISTS(SELECT 1 FROM work_invoice_sessions o WHERE o.session_id=s.id AND o.invoice_id<>?) ORDER BY s.started_at,s.id");$q->execute(array_merge([$id],$jobIds,[$id]));$sessions=$q->fetchAll(PDO::FETCH_ASSOC);
$q=$pdo->prepare("SELECT m.*,EXISTS(SELECT 1 FROM work_invoice_materials x WHERE x.invoice_id=? AND x.material_id=m.id) selected FROM work_materials m WHERE m.job_id IN ($marks) AND COALESCE(m.material_status,'')<>'not_required' AND NOT EXISTS(SELECT 1 FROM work_invoice_materials o WHERE o.material_id=m.id AND o.invoice_id<>?) ORDER BY COALESCE(m.purchase_date,DATE(m.purchased_at)),m.id");$q->execute(array_merge([$id],$jobIds,[$id]));$materials=$q->fetchAll(PDO::FETCH_ASSOC);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reconcile <?=wt_html($invoice['invoice_number'])?></title><style>body{font-family:system-ui;background:#eef2f4;color:#17202a;margin:0}.wrap{max-width:1100px;margin:auto;padding:18px}.card{background:#fff;border-radius:14px;padding:18px;margin:13px 0}.notice{padding:11px;border-radius:9px;background:#fff4d6;border:1px solid #e8bd50}.good{background:#edf8f0;border-color:#96d0a4}.row{border-top:1px solid #dde5ea;padding:10px 0}.muted{color:#667681}.btn{background:#17202a;color:#fff;border:0;border-radius:9px;padding:11px 14px;font-weight:800}.money{float:right}</style></head><body><?php $adminPageTitle='Reconcile '.$invoice['invoice_number'];$adminBreadcrumbs=['Work Tracker'=>'index.php','Customer'=>'customer.php?id='.$invoice['customer_id'],'Invoice reconciliation'=>''];require __DIR__.'/../../includes/admin_nav.php';?><main class="wrap">
<?php if(isset($_GET['imported'])):?><p class="notice good">Invoice imported safely. No labour or materials have been marked as billed yet.</p><?php endif;?><?php if(isset($_GET['saved'])):?><p class="notice good">Reconciliation saved. Selected records will be excluded from future invoices.</p><?php endif;?>
<div class="card"><h1><?=wt_html($invoice['invoice_number'])?> — <?=wt_html($invoice['display_name'])?></h1><p><b>Status:</b> <?=wt_html(strtoupper($invoice['status']))?> · <b>Total:</b> <?=wt_money((float)$invoice['total_amount'])?> · <b>Paid:</b> <?=wt_money((float)$invoice['paid_amount'])?> · <b>Balance:</b> <?=wt_money((float)$invoice['balance_amount'])?></p><p><b>Jobs:</b> <?=wt_html(implode(' | ',array_map(fn($j)=>'#'.$j['id'].' '.$j['job_address'],$jobs)))?></p><?php if((float)$invoice['tax_amount']>0):?><p class="notice">Historical record: Zoho reports <?=wt_money((float)$invoice['tax_amount'])?> tax on this already-issued invoice. Importing it does not alter the Zoho invoice.</p><?php endif;?></div>
<form method="post" action="../../api/work/save_invoice_reconciliation.php" onsubmit="return confirm('Confirm that every selected labour and material record was included in this invoice?');"><input type="hidden" name="invoice_id" value="<?=$id?>"><div class="card"><h2>Labour included in this invoice</h2><p class="muted">Select only work actually covered by the historical invoice.</p><?php foreach($sessions as $s):$amount=(float)$s['hours']*(float)$s['rate'];?><label class="row"><input type="checkbox" name="session_ids[]" value="<?=(int)$s['id']?>" <?=!empty($s['selected'])?'checked':''?>> Job #<?=(int)$s['job_id']?> · <?=wt_html(date('j M Y',strtotime($s['started_at'])))?> · <?=number_format((float)$s['hours'],2)?> hrs — <?=wt_html((string)($s['title']?:$s['notes']?:'Labour'))?><b class="money"><?=wt_money($amount)?></b></label><?php endforeach;?><?php if(!$sessions):?><p>No eligible labour records found.</p><?php endif;?></div>
<div class="card"><h2>Materials and reimbursements included</h2><?php foreach($materials as $m):?><label class="row"><input type="checkbox" name="material_ids[]" value="<?=(int)$m['id']?>" <?=!empty($m['selected'])?'checked':''?>> Job #<?=(int)$m['job_id']?> · <?=wt_html((string)$m['description'])?> · <?=wt_html((string)($m['supplier']??''))?><b class="money"><?=wt_money((float)($m['actual_cost']??$m['cost']??0))?></b></label><?php endforeach;?><?php if(!$materials):?><p>No eligible material records found.</p><?php endif;?></div><p><button class="btn">SAVE BILLED RECORDS</button></p></form></main></body></html>
