<?php
declare(strict_types=1);
require_once __DIR__.'/_auth.php';
require_once __DIR__.'/../../includes/work_tracker.php';
$id=(int)($_GET['id']??0);$job=wt_job($pdo,$id);
$q=$pdo->prepare("SELECT id,original_name,mime_type,supplier,receipt_number,purchase_date,gross_total,status,created_at FROM work_receipts WHERE job_id=? ORDER BY COALESCE(purchase_date,DATE(created_at)) DESC,id DESC");
$q->execute([$id]);$receipts=$q->fetchAll(PDO::FETCH_ASSOC);
$adminPageTitle='Receipt Images';$adminBreadcrumbs=['Work Tracker'=>'index.php','Job'=>'job.php?id='.$id,'Receipt images'=>''];$adminJob=$job;
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Receipt images</title><style>
body{margin:0;font-family:system-ui,-apple-system,sans-serif;background:#f4f6f8;color:#17202a}.wrap{max-width:1180px;margin:auto;padding:18px}.job-pages{display:flex;gap:7px;overflow-x:auto;margin:0 0 14px}.job-pages a{flex:0 0 auto;padding:9px 11px;border:1px solid #cbd5dc;border-radius:9px;background:#fff;color:#17202a;text-decoration:none;font-weight:800}.job-pages a.active{background:#17202a;color:#fff}.receipt-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.receipt-card{background:#fff;border:1px solid #d7e0e6;border-radius:13px;padding:12px;box-shadow:0 2px 9px #0001}.receipt-preview{display:grid;place-items:center;height:300px;background:#edf1f4;border-radius:9px;overflow:hidden}.receipt-preview img{width:100%;height:100%;object-fit:contain}.receipt-preview iframe{width:100%;height:100%;border:0;background:#fff}.receipt-meta{font-size:13px;color:#5e6a74;margin:8px 0}.btn{display:inline-block;background:#17202a;color:#fff;text-decoration:none;border-radius:8px;padding:9px 11px;font-weight:800}.empty{background:#fff;border-radius:13px;padding:25px;text-align:center;color:#65727b}@media(max-width:850px){.receipt-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.receipt-grid{grid-template-columns:1fr}.receipt-preview{height:360px}}
</style></head><body><?php require __DIR__.'/../../includes/admin_nav.php';?><main class="wrap">
<nav class="job-pages"><a href="job.php?id=<?=$id?>">Overview</a><a href="job.php?id=<?=$id?>&view=materials">Materials &amp; receipts</a><a class="active" href="receipt_images.php?id=<?=$id?>">Receipt images</a><a href="job.php?id=<?=$id?>&view=billing">Billing</a></nav>
<p>Browse every stored receipt visually. Select a receipt to open its full-size private copy in a new tab.</p>
<?php if(!$receipts):?><div class="empty"><b>No receipt images have been uploaded for this job.</b><p>Upload receipts from Materials &amp; receipts.</p></div><?php else:?><div class="receipt-grid">
<?php foreach($receipts as $r):$url='receipt_file.php?job_id='.$id.'&receipt_id='.(int)$r['id'];$mime=(string)($r['mime_type']??'');?>
<article class="receipt-card"><a class="receipt-preview" href="<?=$url?>" target="_blank"><?php if(str_starts_with($mime,'image/')):?><img src="<?=$url?>" alt="Receipt <?=wt_html((string)$r['original_name'])?>" loading="lazy"><?php elseif($mime==='application/pdf'):?><iframe src="<?=$url?>#toolbar=0&navpanes=0" title="Receipt PDF preview" loading="lazy"></iframe><?php else:?><strong>Preview unavailable</strong><?php endif;?></a>
<h2 style="font-size:17px;margin:10px 0 3px"><?=wt_html((string)($r['supplier']?:$r['original_name']))?></h2><div class="receipt-meta"><?=wt_html((string)($r['purchase_date']?:$r['created_at']))?><?php if($r['gross_total']!==null):?> · <?=wt_money((float)$r['gross_total'])?><?php endif;?> · <?=wt_html((string)$r['status'])?></div><a class="btn" href="<?=$url?>" target="_blank">View full receipt</a></article>
<?php endforeach;?></div><?php endif;?></main></body></html>
