<?php
declare(strict_types=1);
require_once __DIR__.'/_auth.php';require_once __DIR__.'/../../includes/work_tracker.php';
$jobId=(int)($_GET['id']??0);$job=wt_job($pdo,$jobId);$tasks=wt_job_tasks($pdo,$jobId,false);
$q=$pdo->prepare("SELECT * FROM work_receipts WHERE job_id=? AND status IN ('ready','failed','applied') ORDER BY created_at DESC,id DESC");$q->execute([$jobId]);$receipts=$q->fetchAll(PDO::FETCH_ASSOC);$linesBy=[];if($receipts){$ids=array_column($receipts,'id');$marks=implode(',',array_fill(0,count($ids),'?'));$l=$pdo->prepare("SELECT * FROM work_receipt_lines WHERE receipt_id IN ($marks) ORDER BY receipt_id,line_order,id");$l->execute($ids);foreach($l->fetchAll(PDO::FETCH_ASSOC) as $line)$linesBy[(int)$line['receipt_id']][]=$line;}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Review scanned receipts</title><style>
body{font-family:system-ui;background:#f4f6f8;color:#17202a;margin:0}.wrap{max-width:1100px;margin:auto;padding:16px}.card{background:#fff;border-radius:14px;padding:16px;margin:12px 0;box-shadow:0 2px 10px #0001}.receipt{border:2px solid #d7e1e8;border-radius:12px;padding:14px;margin:14px 0}.failed{border-color:#ca3838;background:#fff1f1}.applied{border-color:#2a9250;background:#f1faf4}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.field label{display:block;font-size:12px;font-weight:850;margin-bottom:4px}input,select{box-sizing:border-box;width:100%;padding:9px;border:1px solid #cbd5dc;border-radius:8px}.btn{display:inline-block;border:0;border-radius:9px;padding:11px 14px;background:#17202a;color:#fff;font-weight:850;text-decoration:none}.line{display:grid;grid-template-columns:34px 1fr 130px 130px;gap:8px;align-items:end;border-top:1px solid #e1e7eb;padding:9px 0}.muted{color:#66717c;font-size:13px}.warning{padding:11px;background:#fff5d8;border:1px solid #e0bd5a;border-radius:9px}@media(max-width:700px){.grid{grid-template-columns:1fr 1fr}.line{grid-template-columns:34px 1fr}.line .money{grid-column:2}.wrap{padding:9px}}</style></head><body><div class="wrap"><p><a href="materials.php?id=<?=$jobId?>#receipts">← Materials / receipts</a></p><h1>Review scanned receipts</h1><p><b><?=wt_html((string)$job['customer_name'])?></b></p><div class="warning"><b>AI/OCR is a draft.</b> Compare every value with the receipt image. Nothing enters the materials ledger or totals until you approve it.</div>
<?php if(isset($_GET['applied'])):?><div class="card"><b>✓ <?=max(0,(int)$_GET['applied'])?> receipt(s) approved and added to the materials ledger.</b></div><?php endif;?>
<form method="post" action="../../api/work/apply_receipt_review.php"><input type="hidden" name="job_id" value="<?=$jobId?>">
<?php foreach($receipts as $receipt):$rid=(int)$receipt['id'];?><div class="receipt <?=wt_html((string)$receipt['status'])?>"><p><a target="_blank" class="btn" href="receipt_file.php?job_id=<?=$jobId?>&receipt_id=<?=$rid?>">VIEW ORIGINAL RECEIPT</a> <span class="muted"><?=wt_html((string)$receipt['original_name'])?> · <?=wt_html((string)$receipt['status'])?></span></p>
<?php if($receipt['status']==='failed'):?><p><b>OCR failed:</b> <?=wt_html((string)$receipt['error_message'])?></p><button class="btn" type="submit" formaction="../../api/work/retry_receipt_ocr.php" name="receipt_id" value="<?=$rid?>">RETRY OCR</button><?php elseif($receipt['status']==='applied'):?><p><b>Already approved and added to the ledger.</b></p><?php else:?><label style="font-size:18px;font-weight:900"><input style="width:24px;height:24px" type="checkbox" name="receipts[<?=$rid?>][apply]" value="1" checked> Approve this receipt</label><div class="grid" style="margin-top:12px">
<div class="field"><label>Supplier</label><input name="receipts[<?=$rid?>][supplier]" value="<?=wt_html((string)$receipt['supplier'])?>"></div><div class="field"><label>Receipt number</label><input name="receipts[<?=$rid?>][receipt_number]" value="<?=wt_html((string)$receipt['receipt_number'])?>"></div><div class="field"><label>Purchase date</label><input type="date" name="receipts[<?=$rid?>][purchase_date]" value="<?=wt_html((string)$receipt['purchase_date'])?>"></div><div class="field"><label>Task</label><select name="receipts[<?=$rid?>][task_id]"><option value="0">Whole job / not assigned</option><?php foreach($tasks as $task):?><option value="<?=$task['id']?>" <?=((int)$receipt['task_id']===(int)$task['id'])?'selected':''?>><?=wt_html((string)$task['title'])?></option><?php endforeach;?></select></div>
<div class="field"><label>Gross total incl. GST</label><input type="number" step=".01" min="0" name="receipts[<?=$rid?>][gross_total]" value="<?=wt_html((string)$receipt['gross_total'])?>"></div><div class="field"><label>GST total</label><input type="number" step=".01" min="0" name="receipts[<?=$rid?>][gst_total]" value="<?=wt_html((string)$receipt['gst_total'])?>"></div><div class="field"><label>Paid by</label><select name="receipts[<?=$rid?>][paid_by]"><option value="mike" <?=$receipt['paid_by']==='mike'?'selected':''?>>Mike</option><option value="customer" <?=$receipt['paid_by']==='customer'?'selected':''?>>Customer</option><option value="other" <?=$receipt['paid_by']==='other'?'selected':''?>>Other</option></select></div><div class="field"><label>Reimbursement</label><select name="receipts[<?=$rid?>][reimbursement_status]"><option value="not_applicable">Not applicable</option><option value="reimbursement_due">Reimbursement due</option><option value="reimbursed">Reimbursed</option><option value="no_reimbursement_due">No reimbursement due</option></select></div><div class="field"><label>Financial treatment</label><select name="receipts[<?=$rid?>][financial_treatment]"><option value="charge_customer">Charge customer</option><option value="included_in_price">Included in agreed price</option><option value="goodwill">Goodwill</option><option value="rectification">Rectification</option></select></div></div>
<?php if($receipt['confidence_note']):?><p class="muted"><b>OCR confidence:</b> <?=wt_html((string)$receipt['confidence_note'])?></p><?php endif;?><h3>Itemised purchases</h3><?php foreach($linesBy[$rid]??[] as $line):$lid=(int)$line['id'];?><div class="line"><input type="checkbox" name="lines[<?=$lid?>][include]" value="1" checked><div class="field"><label>Description</label><input name="lines[<?=$lid?>][description]" value="<?=wt_html((string)$line['description'])?>"></div><div class="field money"><label>Gross incl. GST</label><input type="number" step=".01" min="0" name="lines[<?=$lid?>][gross_amount]" value="<?=wt_html((string)$line['gross_amount'])?>"></div><div class="field money"><label>GST</label><input type="number" step=".01" min="0" name="lines[<?=$lid?>][gst_amount]" value="<?=wt_html((string)$line['gst_amount'])?>"></div></div><?php endforeach;?>
<?php endif;?></div><?php endforeach;?><?php if(array_filter($receipts,static fn(array $r):bool=>$r['status']==='ready')):?><button class="btn" type="submit">APPROVE SELECTED RECEIPTS &amp; ADD MATERIALS</button><?php endif;?></form></div></body></html>
