<?php
declare(strict_types=1);
require_once __DIR__ . '/_auth.php';
require_once __DIR__ . '/../../includes/work_tracker.php';
require_once __DIR__ . '/../../includes/work_social_video.php';

$id = (int)($_GET['id'] ?? 0);
$queuedId = (int)($_GET['queued'] ?? 0);
$job = wt_job($pdo, $id);
$q = $pdo->prepare("SELECT p.*,t.title AS task_title FROM work_task_photos p LEFT JOIN work_tasks t ON t.id=p.task_id WHERE p.job_id=? ORDER BY p.created_at,p.id");
$q->execute([$id]);
$photos = array_values(array_filter($q->fetchAll(PDO::FETCH_ASSOC), static function(array $p): bool {
    return empty($p['file_deleted_at']) && !empty($p['relative_path']) && is_file(wt_task_photo_path((string)$p['relative_path']));
}));
$videos = [];
try { $v=$pdo->prepare("SELECT * FROM work_social_videos WHERE job_id=? ORDER BY id DESC LIMIT 20");$v->execute([$id]);$videos=$v->fetchAll(PDO::FETCH_ASSOC); } catch(Throwable $e) {}
$musicCatalog = wt_social_music_catalog();
function svh(string $v): string { return htmlspecialchars($v, ENT_QUOTES, 'UTF-8'); }
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Social slideshow builder</title><style>
body{font-family:system-ui;background:#f4f6f8;color:#17202a;margin:0}.wrap{max-width:1180px;margin:auto;padding:16px}.card{background:#fff;border:1px solid #dbe3e8;border-radius:12px;padding:16px;margin:13px 0}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.photo{border:2px solid #d7dfe5;border-radius:9px;padding:7px;cursor:pointer}.photo:has(input:checked){border-color:#087f23;background:#eaf8ee}.photo img{width:100%;aspect-ratio:4/5;object-fit:cover;border-radius:6px}.photo input{width:22px;height:22px}.row{display:flex;gap:10px;flex-wrap:wrap}.field{display:flex;flex-direction:column;gap:5px;flex:1;min-width:190px}input,select,textarea{font:inherit;padding:10px;border:1px solid #bfcbd3;border-radius:8px;box-sizing:border-box}textarea{width:100%;min-height:90px}.btn{border:0;border-radius:9px;padding:12px 15px;background:#17202a;color:#fff;font-weight:850;cursor:pointer}.btn.green{background:#087f23}.btn:disabled{opacity:.55;cursor:wait}.muted{font-size:13px;color:#62707b}.review-item{border:1px solid #dbe3e8;border-radius:9px;padding:10px;margin:8px 0}.status{padding:10px;border-radius:8px;background:#eef6ff;margin:8px 0;white-space:pre-wrap}.queue-notice{background:#eaf8ee;border:2px solid #087f23}.video-row{border-top:1px solid #e2e7ea;padding:12px 0}.video-row.highlight{background:#fff8d8;border:2px solid #d6a800;border-radius:9px;padding:12px}.video-preview{display:block;width:min(100%,420px);max-height:560px;margin-top:10px;background:#111;border-radius:9px}.bad{color:#a21e17}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.grid{grid-template-columns:1fr}}</style></head><body><div class="wrap">
<p><a href="social_drafts.php?id=<?=$id?>">&larr; Social drafts</a> · <a href="manage_job.php?id=<?=$id?>">Manage job</a></p>
<h1>Social slideshow builder</h1><p class="muted"><?=svh((string)$job['customer_name'])?> — choose the real job photos in story order. AI aims for an energetic, emotional and click-worthy story while remaining truthful. Customer identity and exact address are excluded.</p>
<?php if($queuedId>0):?><div class="card queue-notice"><strong>Video #<?=$queuedId?> was queued successfully.</strong> Rendering continues in the background. <a href="#video-queue">View its live progress and finished video</a>.</div><?php elseif($videos):?><p><a href="#video-queue">↓ View video queue and latest finished reel</a></p><?php endif;?>

<div class="card"><h2>1. Choose format and photos</h2><div class="row">
<label class="field">Platform<select id="platform"><?php foreach(wt_social_video_platforms() as $k=>$v):?><option value="<?=svh($k)?>"><?=svh($v)?></option><?php endforeach;?></select></label>
<label class="field">Timing without voice-over<select id="imageSeconds"><option value="1.5">Fast — 1.5 seconds</option><option value="1.8" selected>Balanced — 1.8 seconds</option><option value="2.0">Clear — 2 seconds</option></select></label>
<label class="field">Voice-over<select id="voiceEnabled"><option value="0">No voice-over</option><option value="1">AI voice reads narration</option></select></label>
<label class="field">Voice<select id="voice"><?php foreach(wt_social_video_voices() as $k=>$v):?><option value="<?=svh($k)?>"><?=svh($v)?></option><?php endforeach;?></select></label>
<label class="field">Licensed music<select id="music"><?php if($musicCatalog):?><option value="__auto__" selected>Smart rotation — length + variety</option><?php endif;?><option value="">No music</option><?php foreach($musicCatalog as $track):?><option value="<?=svh((string)$track['name'])?>"><?=svh((string)$track['name'])?> — <?=svh(wt_social_duration_label($track['duration_seconds']))?></option><?php endforeach;?></select></label>
</div><p class="muted">Voice-over mode automatically lengthens slides so narration is not cut off. Final duration is capped by the selected photo count and should normally remain under 90 seconds.</p>
<?php if($musicCatalog):?><p class="muted">Automatic music chooses a suitable track length, rotates fairly between equally suitable songs, avoids recently overused tracks, trims to the finished video, and fades out cleanly.</p><?php else:?><p class="muted">Upload at least one licensed track below to enable automatic music.</p><?php endif;?>
<div class="row" style="align-items:center;margin:12px 0"><button class="btn" type="button" id="selectAll">Select all photos</button><button class="btn" type="button" id="clearAll">Clear all</button><strong id="selectedCount">0 photos selected</strong></div><div class="status" id="status" hidden></div>
<div class="grid"><?php foreach($photos as $p):?><label class="photo"><img src="task_photo_admin_view.php?id=<?=(int)$p['id']?>" alt="Job photo"><div><input type="checkbox" class="photo-check" value="<?=(int)$p['id']?>"> <b><?=svh(wt_photo_stage_label((string)$p['photo_type']))?></b></div><div class="muted"><?=svh((string)($p['task_title']??'General job photo'))?></div></label><?php endforeach;?></div>
<?php if(!$photos):?><p class="bad">No source photos are available. Upload fresh task photos first.</p><?php endif;?>
<p><button class="btn" id="generate" <?=$photos?'':'disabled'?>>Generate AI slideshow plan</button></p></div>

<div class="card" id="review" hidden><h2>2. Review and edit</h2><label class="field">Suggested title<input id="title"></label><label class="field">Post caption<textarea id="postCaption"></textarea></label><label class="field">Hashtags<textarea id="hashtags"></textarea></label><div id="items"></div><button class="btn green" id="queue">Approve and queue video</button></div>

<div class="card"><h2>Music library</h2><p class="muted">Upload only music you created, licensed, or are allowed to use commercially. Automatic music matches the finished slideshow length; it does not choose randomly.</p><form method="post" action="../../api/work/upload_social_music.php" enctype="multipart/form-data"><input type="hidden" name="job_id" value="<?=$id?>"><input type="file" name="music" accept="audio/mpeg,audio/mp4,audio/aac,audio/wav,.mp3,.m4a,.aac,.wav" required> <button class="btn">Upload music</button></form></div>

<div class="card" id="video-queue"><h2>Video queue and finished reels</h2><p class="muted">Rendering continues in the background. This section checks progress automatically; you can leave this page and return later.</p><div id="videoList"><?php if(!$videos):?><p class="muted">No videos have been queued for this job yet.</p><?php endif;?><?php foreach($videos as $index=>$v):?><?php $videoId=(int)$v['id'];$isComplete=($v['status']??'')==='complete';$showPlayer=$isComplete&&($videoId===$queuedId||($queuedId===0&&$index===0));?><div class="video-row<?=$videoId===$queuedId?' highlight':''?>" data-video-id="<?=$videoId?>"><b>#<?=$videoId?> <?=svh((string)$v['title'])?></b> — <span class="video-status"><?=svh((string)$v['status'])?></span><?php if($isComplete):?> · <a href="social_video_admin_view.php?id=<?=$videoId?>">Open video</a> · <a href="social_video_admin_view.php?id=<?=$videoId?>&download=1">Download</a> · <a href="social_video_admin_view.php?id=<?=$videoId?>&captions=1">SRT captions</a><?php if($showPlayer):?><video class="video-preview" controls preload="metadata" src="social_video_admin_view.php?id=<?=$videoId?>">Your browser cannot play this video.</video><?php endif;?><?php else:?><div class="muted">Please leave this page open to watch the status, or come back later. The finished video and download link will appear here.</div><?php endif;?><details><summary>Suggested post title / caption</summary><h3><?=svh((string)$v['title'])?></h3><div style="white-space:pre-wrap"><?=svh((string)$v['post_caption'])?></div><?php if(!empty($v['hashtags'])):?><p><?=svh((string)$v['hashtags'])?></p><?php endif;?></details><?php if(!empty($v['error_message'])):?><div class="bad"><?=svh((string)$v['error_message'])?></div><?php endif;?></div><?php endforeach;?></div></div>
</div><script>
const jobId=<?=$id?>;let currentPlan=null;const statusBox=document.getElementById('status');
function selected(){return [...document.querySelectorAll('.photo-check:checked')].map(x=>Number(x.value));}
function updateSelectedCount(){const n=selected().length;const voice=document.getElementById('voiceEnabled').value==='1';const seconds=voice?(n>25?n*1.8:n*2.2):n*Number(document.getElementById('imageSeconds').value||1.8);document.getElementById('selectedCount').textContent=`${n} photo${n===1?'':'s'} selected · estimated ${Math.round(seconds)} seconds${voice?' with scene-based narration':''}`;}
function showStatus(text,bad=false){statusBox.hidden=false;statusBox.textContent=text;statusBox.style.background=bad?'#fde8e8':'#eef6ff';statusBox.scrollIntoView({behavior:'smooth',block:'center'});}
document.getElementById('selectAll').onclick=()=>{document.querySelectorAll('.photo-check').forEach(x=>x.checked=true);updateSelectedCount();};
document.getElementById('clearAll').onclick=()=>{document.querySelectorAll('.photo-check').forEach(x=>x.checked=false);updateSelectedCount();};
document.querySelectorAll('.photo-check').forEach(x=>x.addEventListener('change',updateSelectedCount));
document.getElementById('voiceEnabled').addEventListener('change',updateSelectedCount);
document.getElementById('imageSeconds').addEventListener('change',updateSelectedCount);
document.getElementById('generate').onclick=async()=>{const ids=selected();if(ids.length<2){showStatus('Choose at least two photos, or press Select all photos.',true);return;}showStatus('Creating an energetic, emotionally engaging slideshow story...');const fd=new FormData();fd.set('job_id',jobId);fd.set('platform',document.getElementById('platform').value);fd.set('photo_ids',ids.join(','));fd.set('voiceover_enabled',document.getElementById('voiceEnabled').value);fd.set('image_seconds',document.getElementById('imageSeconds').value);try{const r=await fetch('../../api/work/generate_social_video_plan.php',{method:'POST',body:fd});const d=await r.json();if(!d.ok)throw new Error(d.error||'Plan failed');currentPlan=d.plan;document.getElementById('title').value=d.plan.title||'';document.getElementById('postCaption').value=d.plan.post_caption||'';document.getElementById('hashtags').value=(d.plan.hashtags||[]).join(' ');document.getElementById('items').innerHTML=(d.plan.items||[]).map((item,i)=>`<div class="review-item" data-photo-id="${item.photo_id}"><b>Slide ${i+1}</b><label class="field">On-screen caption<input class="screen-caption" value="${String(item.screen_caption||'').replaceAll('&','&amp;').replaceAll('"','&quot;')}"></label><label class="field">Voice narration<textarea class="narration">${String(item.narration_text||'').replaceAll('&','&amp;').replaceAll('<','&lt;')}</textarea></label><label>Seconds <input class="duration" type="number" min="1" max="12" step="0.1" value="${item.duration_seconds||1.8}"></label></div>`).join('');document.getElementById('review').hidden=false;showStatus('Story plan ready. Review every exciting claim and caption before queueing.');document.getElementById('review').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){showStatus(e.message,true);}};
document.getElementById('queue').onclick=async()=>{if(!currentPlan)return;const button=document.getElementById('queue');const items=[...document.querySelectorAll('.review-item')].map(x=>({photo_id:Number(x.dataset.photoId),screen_caption:x.querySelector('.screen-caption').value,narration_text:x.querySelector('.narration').value,duration_seconds:Number(x.querySelector('.duration').value)}));const payload={job_id:jobId,platform:document.getElementById('platform').value,title:document.getElementById('title').value,post_caption:document.getElementById('postCaption').value,hashtags:document.getElementById('hashtags').value,voiceover_enabled:document.getElementById('voiceEnabled').value,voice_name:document.getElementById('voice').value,music_file:document.getElementById('music').value,image_seconds:document.getElementById('imageSeconds').value,items};button.disabled=true;button.textContent='Queueing video…';showStatus('Queueing video and starting the renderer...');try{const r=await fetch('../../api/work/queue_social_video.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!d.ok)throw new Error(d.error||'Queue failed');showStatus(`Video #${d.id} was queued successfully. Opening its live progress now…`,false);location.href=`social_video_builder.php?id=${jobId}&queued=${d.id}#video-queue`;}catch(e){button.disabled=false;button.textContent='Approve and queue video';showStatus(e.message,true);}};
async function poll(){for(const row of document.querySelectorAll('[data-video-id]')){const id=row.dataset.videoId;const r=await fetch(`../../api/work/social_video_status.php?id=${id}`);if(!r.ok)continue;const d=await r.json();const el=row.querySelector('.video-status');if(el)el.textContent=d.status;if((d.status==='complete'||d.status==='failed')&&!row.querySelector('a')&&!row.querySelector('.bad'))location.href=`social_video_builder.php?id=${jobId}&queued=${id}#video-queue`;}}setInterval(poll,5000);
if(location.hash==='#video-queue'){requestAnimationFrame(()=>document.getElementById('video-queue')?.scrollIntoView({block:'start'}));}
</script></body></html>
