<?php
declare(strict_types=1);
require_once __DIR__ . '/_auth.php';
require_once __DIR__ . '/../../includes/work_tracker.php';
$jobId=(int)($_GET['id']??0);$requestId=(int)($_GET['request_id']??0);$job=wt_job($pdo,$jobId);
$q=$pdo->prepare('SELECT * FROM work_task_update_requests WHERE id=? AND job_id=? LIMIT 1');$q->execute([$requestId,$jobId]);$request=$q->fetch(PDO::FETCH_ASSOC);
if(!$request){http_response_code(404);exit('Task update review not found.');}
$proposal=json_decode((string)($request['proposal_json']??''),true);if(!is_array($proposal))$proposal=['summary'=>'','items'=>[]];
$snapshot=json_decode((string)($request['existing_tasks_snapshot_json']??''),true);if(!is_array($snapshot))$snapshot=[];$taskById=[];foreach($snapshot as $task)$taskById[(int)($task['id']??0)]=$task;
$fq=$pdo->prepare('SELECT * FROM work_task_update_files WHERE request_id=? AND job_id=? ORDER BY id');$fq->execute([$requestId,$jobId]);$files=$fq->fetchAll(PDO::FETCH_ASSOC);
$labels=['add'=>'Add new task','update'=>'Update existing task wording','already_covered'=>'Already covered — no change'];$adminPageTitle='Task Update Review';$adminBreadcrumbs=['Work Tracker'=>'index.php','Task update'=>''];$adminJob=$job;require __DIR__.'/../../includes/admin_nav.php';
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Review AI task comparison</title><style>
body{font-family:system-ui;background:#f4f6f8;color:#17202a;margin:0}.wrap{max-width:1050px;margin:auto;padding:18px}.card{background:#fff;border-radius:14px;padding:16px;margin:12px 0;box-shadow:0 2px 10px #0001}.item{border:2px solid #dce3e8;border-radius:12px;padding:14px;margin:12px 0}.item.add{border-color:#75b98a;background:#f0faf3}.item.update{border-color:#7aa9d2;background:#f1f7fc}.item.already_covered{background:#f5f6f7;color:#5d6870}.pill{display:inline-block;padding:5px 9px;border-radius:999px;background:#e7edf2;font-size:12px;font-weight:900}.btn{display:inline-block;background:#17202a;color:#fff;border:0;border-radius:9px;padding:11px 14px;font-weight:850;text-decoration:none;cursor:pointer}.muted{color:#64717b;font-size:13px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.box{background:#fff;border:1px solid #dce3e8;border-radius:9px;padding:11px}.selectline{display:flex;gap:10px;align-items:flex-start}.selectline input{width:24px;height:24px}.warning{background:#fff4d8;border:1px solid #e1bd59;border-radius:10px;padding:12px}@media(max-width:700px){.grid{grid-template-columns:1fr}.wrap{padding:10px}}
</style></head><body><div class="wrap"><p><a href="manage_job.php?id=<?=$jobId?>#customer-request">← Manage job</a></p><h1>Review AI task comparison</h1><p><b><?=wt_html((string)$job['customer_name'])?></b> · Submission #<?=$requestId?> · <?=wt_html(ucfirst((string)$request['source']))?></p>
<?php if($request['status']==='failed'):?><div class="warning"><b>Comparison failed:</b> <?=wt_html((string)$request['error_message'])?></div><?php elseif($request['status']==='applied'):?><div class="card"><b>✓ This comparison was applied <?=wt_html((string)$request['applied_at'])?>.</b></div><?php endif;?>
<div class="card"><h2>Submitted evidence</h2><?php if(trim((string)$request['source_text'])!==''):?><div style="white-space:pre-wrap"><?=wt_html((string)$request['source_text'])?></div><?php endif;?><?php foreach($files as $file):?><p><a target="_blank" href="task_update_file.php?job_id=<?=$jobId?>&file_id=<?=$file['id']?>">View <?=wt_html((string)$file['original_name'])?></a></p><?php endforeach;?></div>
<?php if(!empty($proposal['summary'])):?><div class="card"><h2>AI comparison summary</h2><p><?=nl2br(wt_html((string)$proposal['summary']))?></p></div><?php endif;?>
<?php if($request['status']==='ready'):?><form method="post" action="../../api/work/apply_task_update.php"><input type="hidden" name="job_id" value="<?=$jobId?>"><input type="hidden" name="request_id" value="<?=$requestId?>"><div class="warning"><b>Nothing has changed yet.</b> Tick only the additions and updates you approve. Existing task IDs, status, photos and recorded time will be preserved.</div>
<?php foreach(($proposal['items']??[]) as $index=>$item):$action=(string)($item['action']??'already_covered');$task=is_array($item['task']??null)?$item['task']:[];$matched=$taskById[(int)($item['matched_task_id']??0)]??null;?><div class="item <?=wt_html($action)?>"><div class="selectline"><?php if($action!=='already_covered'):?><input type="checkbox" name="selected[]" value="<?=$index?>" checked aria-label="Apply this suggestion"><?php endif;?><div style="flex:1"><span class="pill"><?=wt_html($labels[$action]??$action)?></span><h2><?=wt_html((string)($task['title']??($matched['title']??'Covered item')))?></h2><p><b>Why:</b> <?=wt_html((string)($item['reason']??''))?></p><?php if($matched):?><div class="grid"><div class="box"><b>Existing task #<?= (int)$matched['id'] ?></b><p><?=wt_html((string)$matched['title'])?></p><div class="muted"><?=nl2br(wt_html((string)($matched['description']??'')))?></div><p class="muted">Status: <?=wt_html(str_replace('_',' ',(string)$matched['status']))?></p></div><div class="box"><b>Proposed wording</b><p><?=wt_html((string)($task['title']??''))?></p><div class="muted"><?=nl2br(wt_html((string)($task['description']??'')))?></div></div></div><?php else:?><p><?=nl2br(wt_html((string)($task['description']??'')))?></p><?php endif;?></div></div></div><?php endforeach;?>
<button class="btn" type="submit">APPLY SELECTED TASK CHANGES</button></form><?php endif;?></div></body></html>
