<?php
declare(strict_types=1);
$base=($_SERVER['HTTP_HOST']??'')==='localhost'?'/mike_of_all_trades':'';$current=$_SERVER['REQUEST_URI']??'';$adminPageTitle=$adminPageTitle??'Administration';$adminBreadcrumbs=$adminBreadcrumbs??[];$adminJob=$adminJob??null;$adminJobId=is_array($adminJob)?(int)($adminJob['id']??0):0;
if(!function_exists('admin_nav_active')){function admin_nav_active(string $needle,string $current):string{return str_contains($current,$needle)?' active':'';}}
?>
<style>
.admin-shell{font-family:system-ui,-apple-system,sans-serif;background:#111827;color:#fff;position:sticky;top:0;z-index:1000;box-shadow:0 2px 10px #0003}.admin-nav{border-bottom:1px solid #374151;padding:9px 14px}.admin-nav-inner,.admin-context-inner{max-width:1200px;margin:auto;display:flex;gap:8px;align-items:center;flex-wrap:wrap}.admin-nav a{color:#fff;text-decoration:none;padding:8px 11px;border-radius:8px;font-size:14px;background:#1f2937}.admin-nav a:hover,.admin-nav a.active{background:#f39200;color:#111}.admin-nav-spacer{flex:1}.admin-search-wrap{position:relative;flex:0 1 360px}.admin-search{width:100%;box-sizing:border-box;border:1px solid #64748b;border-radius:9px;padding:9px 12px;background:#fff;color:#111827;font:inherit}.admin-search-results{display:none;position:absolute;top:calc(100% + 5px);left:0;right:0;min-width:320px;max-height:70vh;overflow:auto;background:#fff;color:#17202a;border:1px solid #cbd5e1;border-radius:10px;box-shadow:0 12px 30px #0004}.admin-search-results.open{display:block}.admin-search-results a{display:block;background:#fff!important;color:#17202a!important;border-radius:0;padding:10px 12px;border-bottom:1px solid #edf0f2}.admin-search-results a:hover,.admin-search-results a:focus{background:#fff4df!important}.admin-search-results small{display:block;color:#64748b;margin-top:2px}.admin-search-empty{padding:12px;color:#64748b}.admin-context{background:#fff;color:#17202a;padding:11px 14px;border-bottom:1px solid #d8dee6}.admin-context-inner{align-items:flex-start}.admin-heading{flex:1;min-width:240px}.admin-heading h1{font-size:20px!important;line-height:1.2!important;margin:2px 0!important;color:#17202a!important}.admin-crumbs{font-size:12px;color:#64748b;margin-bottom:3px}.admin-crumbs a{color:#365c83}.admin-job-context{font-size:13px;color:#475569;margin-top:4px}.admin-related{display:flex;gap:6px;flex-wrap:wrap}.admin-related a{color:#17202a;text-decoration:none;border:1px solid #cbd5e1;border-radius:8px;padding:7px 9px;font-size:13px;background:#f8fafc}.admin-related a:hover{border-color:#f39200;background:#fff4df}
@media(max-width:760px){.admin-shell{position:static}.admin-nav-inner{gap:6px}.admin-nav a{font-size:13px;padding:8px;flex:1 1 auto;text-align:center}.admin-nav-spacer{display:none}.admin-search-wrap{order:-1;flex:1 0 100%}.admin-search-results{min-width:0}.admin-context-inner{display:block}.admin-related{margin-top:9px}.admin-heading h1{font-size:18px!important}}
</style>
<header class="admin-shell"><nav class="admin-nav" aria-label="Admin navigation"><div class="admin-nav-inner">
<a class="<?=admin_nav_active('/admin/dashboard.php',$current)?>" href="<?=$base?>/admin/dashboard.php">Calendar</a><a class="<?=admin_nav_active('/admin/work/',$current)?>" href="<?=$base?>/admin/work/index.php">Work Tracker</a><a href="<?=$base?>/admin/work/new.php">+ New Job</a><a class="<?=admin_nav_active('/admin/ai_estimates',$current)?>" href="<?=$base?>/admin/ai_estimates.php">AI Estimates</a><span class="admin-nav-spacer"></span>
<div class="admin-search-wrap"><label for="adminFindAnything" style="position:absolute;left:-9999px">Find anything</label><input id="adminFindAnything" class="admin-search" type="search" autocomplete="off" placeholder="Find anything — slideshow, receipt, customer…"><div id="adminSearchResults" class="admin-search-results" role="listbox"></div></div><a href="<?=$base?>/" target="_blank">Website</a><a href="<?=$base?>/logout.php">Logout</a>
</div></nav><div class="admin-context"><div class="admin-context-inner"><div class="admin-heading"><div class="admin-crumbs"><a href="<?=$base?>/admin/dashboard.php">Admin</a><?php foreach($adminBreadcrumbs as $label=>$href):?> · <?php if($href):?><a href="<?=htmlspecialchars((string)$href,ENT_QUOTES,'UTF-8')?>"><?=htmlspecialchars((string)$label,ENT_QUOTES,'UTF-8')?></a><?php else:?><?=htmlspecialchars((string)$label,ENT_QUOTES,'UTF-8')?><?php endif;?><?php endforeach;?></div><h1><?=htmlspecialchars((string)$adminPageTitle,ENT_QUOTES,'UTF-8')?></h1><?php if(is_array($adminJob)):?><div class="admin-job-context">Job #<?=$adminJobId?> · <?=htmlspecialchars((string)($adminJob['customer_name']??''),ENT_QUOTES,'UTF-8')?><?php if(!empty($adminJob['job_address'])):?> · <?=htmlspecialchars((string)$adminJob['job_address'],ENT_QUOTES,'UTF-8')?><?php endif;?></div><?php endif;?></div><?php if($adminJobId):?><div class="admin-related"><a href="<?=$base?>/admin/work/manage_job.php?id=<?=$adminJobId?>">Manage job</a><a href="<?=$base?>/admin/work/task_photos.php?id=<?=$adminJobId?>">Photos</a><a href="<?=$base?>/admin/work/social_drafts.php?id=<?=$adminJobId?>">Social drafts</a><a href="<?=$base?>/admin/work/social_video_builder.php?id=<?=$adminJobId?>">Reels</a><a href="<?=$base?>/admin/work/materials.php?id=<?=$adminJobId?>">Materials</a></div><?php endif;?></div></div></header>
<script>
(()=>{const input=document.getElementById('adminFindAnything'),box=document.getElementById('adminSearchResults');if(!input||!box)return;let timer,controller;const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));function close(){box.classList.remove('open')}input.addEventListener('input',()=>{clearTimeout(timer);const q=input.value.trim();if(!q){close();box.innerHTML='';return}timer=setTimeout(async()=>{controller?.abort();controller=new AbortController();try{const r=await fetch('<?=$base?>/api/work/admin_search.php?q='+encodeURIComponent(q)+'&job_id=<?=$adminJobId?>',{signal:controller.signal,credentials:'same-origin'});const d=await r.json(),rows=Array.isArray(d.results)?d.results:[];box.innerHTML=rows.length?rows.map(x=>`<a role="option" href="${esc(x.url)}"><strong>${esc(x.title)}</strong><small>${esc(x.description||x.type||'')}</small></a>`).join(''):'<div class="admin-search-empty">No matching page, action, job or customer.</div>';box.classList.add('open')}catch(e){if(e.name!=='AbortError'){box.innerHTML='<div class="admin-search-empty">Search is temporarily unavailable.</div>';box.classList.add('open')}}},180)});input.addEventListener('keydown',e=>{if(e.key==='Escape'){close();input.blur()}if(e.key==='Enter'){const first=box.querySelector('a');if(first){e.preventDefault();location.href=first.href}}});document.addEventListener('click',e=>{if(!e.target.closest('.admin-search-wrap'))close()})})();
</script>
