CREATE TABLE IF NOT EXISTS work_task_update_requests (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    job_id INT UNSIGNED NOT NULL,
    source ENUM('mike','customer') NOT NULL,
    submitted_by VARCHAR(150) NOT NULL,
    source_text LONGTEXT NULL,
    status ENUM('processing','ready','applied','failed','cancelled') NOT NULL DEFAULT 'processing',
    existing_tasks_snapshot_json LONGTEXT NOT NULL,
    proposal_json LONGTEXT NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    applied_at DATETIME NULL,
    applied_by VARCHAR(150) NULL,
    CONSTRAINT fk_task_update_request_job FOREIGN KEY (job_id) REFERENCES work_jobs(id) ON DELETE CASCADE,
    INDEX idx_task_update_job_status (job_id,status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS work_task_update_files (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    request_id BIGINT UNSIGNED NOT NULL,
    job_id INT UNSIGNED NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    relative_path VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL,
    sha256 CHAR(64) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_task_update_file_request FOREIGN KEY (request_id) REFERENCES work_task_update_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_update_file_job FOREIGN KEY (job_id) REFERENCES work_jobs(id) ON DELETE CASCADE,
    INDEX idx_task_update_files_request (request_id),
    INDEX idx_task_update_files_job (job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS work_receipts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    job_id INT UNSIGNED NOT NULL,
    task_id INT UNSIGNED NULL,
    session_id INT UNSIGNED NULL,
    original_name VARCHAR(255) NOT NULL,
    relative_path VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL,
    sha256 CHAR(64) NOT NULL,
    status ENUM('processing','ready','applied','duplicate','failed','cancelled') NOT NULL DEFAULT 'processing',
    supplier VARCHAR(190) NULL,
    receipt_number VARCHAR(120) NULL,
    purchase_date DATE NULL,
    gross_total DECIMAL(12,2) NULL,
    gst_total DECIMAL(12,2) NULL,
    net_total DECIMAL(12,2) NULL,
    paid_by ENUM('mike','customer','other') NOT NULL DEFAULT 'mike',
    reimbursement_status ENUM('not_applicable','reimbursement_due','reimbursed','no_reimbursement_due') NOT NULL DEFAULT 'not_applicable',
    financial_treatment ENUM('charge_customer','included_in_price','goodwill','rectification') NOT NULL DEFAULT 'charge_customer',
    confidence_note VARCHAR(500) NULL,
    raw_ai_json LONGTEXT NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at DATETIME NULL,
    reviewed_by VARCHAR(150) NULL,
    CONSTRAINT fk_work_receipt_job FOREIGN KEY (job_id) REFERENCES work_jobs(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_receipt_task FOREIGN KEY (task_id) REFERENCES work_tasks(id) ON DELETE SET NULL,
    CONSTRAINT fk_work_receipt_session FOREIGN KEY (session_id) REFERENCES work_sessions(id) ON DELETE SET NULL,
    UNIQUE KEY uq_work_receipt_job_sha (job_id,sha256),
    INDEX idx_work_receipt_job_status (job_id,status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS work_receipt_lines (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    receipt_id BIGINT UNSIGNED NOT NULL,
    job_id INT UNSIGNED NOT NULL,
    task_id INT UNSIGNED NULL,
    line_order INT UNSIGNED NOT NULL DEFAULT 10,
    description VARCHAR(500) NOT NULL,
    quantity DECIMAL(12,3) NULL,
    unit_price DECIMAL(12,2) NULL,
    gross_amount DECIMAL(12,2) NULL,
    gst_amount DECIMAL(12,2) NULL,
    net_amount DECIMAL(12,2) NULL,
    selected_for_ledger TINYINT(1) NOT NULL DEFAULT 1,
    material_id INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_receipt_line_receipt FOREIGN KEY (receipt_id) REFERENCES work_receipts(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_receipt_line_job FOREIGN KEY (job_id) REFERENCES work_jobs(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_receipt_line_task FOREIGN KEY (task_id) REFERENCES work_tasks(id) ON DELETE SET NULL,
    CONSTRAINT fk_work_receipt_line_material FOREIGN KEY (material_id) REFERENCES work_materials(id) ON DELETE SET NULL,
    INDEX idx_work_receipt_line_receipt (receipt_id,line_order),
    INDEX idx_work_receipt_line_job (job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
