CREATE TABLE IF NOT EXISTS work_photo_upload_queue (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    batch_token VARCHAR(40) NOT NULL,
    client_file_key VARCHAR(80) NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    fallback_task_id BIGINT UNSIGNED NOT NULL,
    assignment_mode VARCHAR(20) NOT NULL DEFAULT 'auto',
    fallback_photo_type VARCHAR(20) NOT NULL DEFAULT 'progress',
    bulk_note TEXT NULL,
    client_mtime_ms BIGINT NULL,
    original_name VARCHAR(255) NOT NULL,
    staging_relative_path VARCHAR(500) NOT NULL,
    detected_mime VARCHAR(100) NOT NULL,
    original_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'queued',
    attempts INT UNSIGNED NOT NULL DEFAULT 0,
    photo_id BIGINT UNSIGNED NULL,
    assignment_method VARCHAR(80) NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_work_photo_queue_file (batch_token,client_file_key),
    KEY idx_work_photo_queue_status (status,id),
    KEY idx_work_photo_queue_job (job_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
